name: dart_collection_sampler
description: a small library implementing methods to sample items from collections
version: 3.0.0
homepage: https://github.com/stevesea/dart_collection_sampler
repository: https://github.com/stevesea/dart_collection_sampler

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dart_dice_parser: ^4.0.5

dev_dependencies:
  args: ^2.3.1
  lint: ^1.0.0
  mocktail: ^0.3.0
  test: ^1.21.6
