name: dart_collection_sampler
description: a small library implementing methods to sample items from collections
version: 0.6.0
homepage: https://github.com/stevesea/dart_collection_sampler
authors:
  - steve christensen <adventuresmith.rpg@gmail.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  dart_dice_parser: ^0.2.0

dev_dependencies:
  test: ^1.3.4
  mockito: ^3.0.0
  args: ^1.5.0
