name: dart_collection_sampler
description: a small library implementing methods to sample items from collections
version: 1.0.1
homepage: https://github.com/stevesea/dart_collection_sampler
authors:
  - steve christensen <adventuresmith.rpg@gmail.com>

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  dart_dice_parser: ^1.3.1

dev_dependencies:
  test: ^1.6.4
  mockito: ^4.1.0
  args: ^1.5.2
